# CS156 (Introduction to AI), Spring 2021
# <u> Homework 13 submission </u>

## Roster Name: Azael Zamora
## Student ID: 013528931
## Email Address: azael.zamora12@gmail.com

# <u> References and sources </u>

* https://www.kaggle.com/charel/learn-by-example-reinforcement-learning-with-gym
* RL.Q-learning.taxi_game.ipynb

In [1]:
import numpy as np
import pandas as pd
import gym

In [2]:
np.random.seed(42)

* S : starting point, safe
* F : frozen surface, safe
* H : hole, fall to your doom
* G : goal, where the frisbee is located

In [4]:
FrozenLakeEnv = gym.make("FrozenLake-v0", is_slippery = False).env 
FrozenLakeEnv.seed(42)
FrozenLakeEnv.reset()
FrozenLakeEnv.render()

print("Action Space {}".format(FrozenLakeEnv.action_space))
print("State Space {}".format(FrozenLakeEnv.observation_space))


SFFF
FHFH
FFFH
HFFG
Action Space Discrete(4)
State Space Discrete(16)


# Q-Learning Algorithm w/ Stochasticity

In [5]:
qtable = np.zeros([FrozenLakeEnv.observation_space.n, FrozenLakeEnv.action_space.n])
gamma = 0.95  # discount factor
alpha = 0.01  # learning rate
epsilon = 0.5 # threshold of stochasticity

for episode in range(1, 10001):
  done = False
  reward_total = 0
  state = FrozenLakeEnv.reset()

  while done != True:
    explore = np.random.uniform(0, 1)

    if explore < epsilon:
      action = FrozenLakeEnv.action_space.sample()  # explore
    else:
      action = np.argmax(qtable[state])  # exploitation
    
    state_tmp, reward, done, info = FrozenLakeEnv.step(action) # take the action
    qtable[state, action] += alpha * (reward + gamma * np.max(qtable[state_tmp]) - qtable[state, action])
    state = state_tmp
    reward_total = reward_total + reward
  
  if episode % 100 == 0:
    print('Episode {} Total Reward: {}'.format(episode,reward_total))

Episode 100 Total Reward: 0.0
Episode 200 Total Reward: 0.0
Episode 300 Total Reward: 0.0
Episode 400 Total Reward: 0.0
Episode 500 Total Reward: 0.0
Episode 600 Total Reward: 0.0
Episode 700 Total Reward: 0.0
Episode 800 Total Reward: 0.0
Episode 900 Total Reward: 0.0
Episode 1000 Total Reward: 0.0
Episode 1100 Total Reward: 0.0
Episode 1200 Total Reward: 0.0
Episode 1300 Total Reward: 1.0
Episode 1400 Total Reward: 1.0
Episode 1500 Total Reward: 1.0
Episode 1600 Total Reward: 0.0
Episode 1700 Total Reward: 0.0
Episode 1800 Total Reward: 1.0
Episode 1900 Total Reward: 1.0
Episode 2000 Total Reward: 0.0
Episode 2100 Total Reward: 0.0
Episode 2200 Total Reward: 0.0
Episode 2300 Total Reward: 0.0
Episode 2400 Total Reward: 0.0
Episode 2500 Total Reward: 0.0
Episode 2600 Total Reward: 1.0
Episode 2700 Total Reward: 1.0
Episode 2800 Total Reward: 0.0
Episode 2900 Total Reward: 0.0
Episode 3000 Total Reward: 1.0
Episode 3100 Total Reward: 0.0
Episode 3200 Total Reward: 0.0
Episode 3300 Tota

In [6]:
print('Q-table after:')
print(qtable)

Q-table after:
[[0.73509188 0.77378094 0.69833257 0.73509188]
 [0.73509049 0.         0.61160817 0.62231666]
 [0.31120732 0.80272946 0.03373014 0.2451871 ]
 [0.1812748  0.         0.00223652 0.00347698]
 [0.77378051 0.81450625 0.         0.7350916 ]
 [0.         0.         0.         0.        ]
 [0.         0.90149722 0.         0.37150653]
 [0.         0.         0.         0.        ]
 [0.81449969 0.         0.857375   0.77377748]
 [0.81433136 0.90233415 0.9025     0.        ]
 [0.85661431 0.95       0.         0.85011613]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.8223116  0.94999733 0.75812   ]
 [0.90119149 0.94882531 1.         0.90185454]
 [0.         0.         0.         0.        ]]


In [7]:
reward_total = 0
state = FrozenLakeEnv.reset()
done = False

FrozenLakeEnv.render()

while done != True:
  action = np.argmax(qtable[state])
  state, reward, done, info = FrozenLakeEnv.step(action)
  reward_total += reward 
  FrozenLakeEnv.render()

print("Reward: ", reward_total)


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Reward:  1.0
