# This notebook is an introduction to tensorts in TensorFlow framework

In [15]:
import tensorflow as tf
import numpy as np

In [92]:
np.random.seed(42)

### Play around with some basic tensor operations

### Create a constant tensor

https://www.tensorflow.org/api_docs/python/tf/constant

dtype:   
tf.string: String variable   
tf.float32: Floating point variable   
tf.int16: Integer variable   
tf.int32: Integer variable   
tf.int64: Integer variable   

tf.constant(
    value, dtype=None, shape=None, name='Const'
)

In [4]:
var1 = tf.constant(10, tf.int16)
print(var1)

tf.Tensor(10, shape=(), dtype=int16)


In [6]:
var2 = tf.constant(10, tf.int16, name="myVar2")
print(var2)

tf.Tensor(10, shape=(), dtype=int16)


In [7]:
var3 = tf.constant(10.5, tf.float32)
print(var3)

tf.Tensor(10.5, shape=(), dtype=float32)


In [8]:
var4 = tf.constant("MyString", tf.string)
print(var4)

tf.Tensor(b'MyString', shape=(), dtype=string)


In [10]:
var5 = tf.constant([1,2,3,4,5], tf.int16)
print(var5)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [11]:
var6 = tf.constant([1.,2.,3.,4.,5.], tf.float32)
print(var6)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [12]:
var7 = tf.constant(["1","2","3"], tf.string)
print(var7)

tf.Tensor([b'1' b'2' b'3'], shape=(3,), dtype=string)


In [14]:
var8 = tf.constant([ [1, 2],  
                     [3, 4],
                     [5, 6] 
                   ],tf.int16)  
print(var8)  

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int16)


In [16]:
var9 = tf.constant(np.matrix('1 2; 3 4; 5 6'),tf.int16)  
print(var9)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int16)


In [18]:
print(var9.shape)

(3, 2)


In [17]:
# create vector of zeros
var10 = tf.zeros(15)
print(var10) 

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(15,), dtype=float32)


In [22]:
# create vector of ones in a shape of matrix, get the shape of another tensor
var11 = tf.ones(var9.shape)
print(var11)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [23]:
print(var11.dtype)

<dtype: 'float32'>


In [24]:
# casting as another type
var12 = tf.constant(5, tf.float32)
var13 = tf.cast(var12, tf.int16)

print(var12.dtype)  
print(var13.dtype)

<dtype: 'float32'>
<dtype: 'int16'>


### Generating tensors based on well known distributions

In [67]:
randNorm = tf.random.normal(shape = (3,2), mean=5.0, stddev=2.0)
print(randNorm)

tf.Tensor(
[[6.911309  6.964861 ]
 [2.4212408 3.7391064]
 [3.2423325 5.9750566]], shape=(3, 2), dtype=float32)


In [69]:
randUniform = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(randUniform)

tf.Tensor(
[[3 8]
 [6 5]], shape=(2, 2), dtype=int32)


### Useful operations

- tf.exp(a)
- tf.sqrt(a)
- tf.add(a,b)
- tf.substract(a,b)
- tf.multiply(a,b)
- tf.div(a,b)
- tf.pow(a,b)

https://www.tensorflow.org/api_docs/python/tf/math

In [31]:
var14 = tf.constant(np.matrix('1 2; 3 4; 5 6'),tf.float32)
print(var14)
var15 = tf.ones(var14.shape,tf.float32)
print(var15)

print(tf.add(var14, var15))

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[2. 3.]
 [4. 5.]
 [6. 7.]], shape=(3, 2), dtype=float32)


In [33]:
# notice, this is an element-wise multiplication, not a matrix multiplication
var16 = tf.constant(np.matrix('1 2; 3 4; 5 6'),tf.float32)
var17 = tf.constant(np.matrix('6 5; 4 3; 2 1'),tf.int16)

print(tf.multiply(var16, tf.cast(var17, tf.float32)))

tf.Tensor(
[[ 6. 10.]
 [12. 12.]
 [10.  6.]], shape=(3, 2), dtype=float32)


In [64]:
print(tf.reduce_mean(tf.constant([1,2,3,4,5], tf.float32)))

tf.Tensor(3.0, shape=(), dtype=float32)


In [90]:
# you can also do this:
x1 = tf.Variable(3, name = "x1")
x2 = tf.Variable(5, name = "x2")
y = x1 + x2
print(y)

print("\nCan also extract scalar value:", y.numpy())

tf.Tensor(8, shape=(), dtype=int32)

Can also extract scalar value: 8


### Create a variable tensor

tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)

Use get_variable for older versions of TensorFlow

In [40]:
var17 = tf.Variable("my variable")
print(var17)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'my variable'>


In [41]:
var18 = tf.Variable(1.)
print(var18)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [42]:
var19 = tf.Variable(np.matrix('1 2; 3 4; 5 6'))
print(var19)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>


### TensorFlow graph operations

@tf.function converts a Python function to its graph representation

In [76]:
@tf.function
def multiply(x,y):
    return x*y

@tf.function
def add(x,y):
    return x+y

x1 = tf.constant(2, name="x1", dtype=tf.float32)
x2 = tf.constant(5, name="x2", dtype=tf.float32)
x3 = tf.constant(12, name="x3", dtype=tf.float32)

multiply(add(x1,x2),x3).numpy()

84.0

In [77]:
# same result:
tf.multiply(tf.add(x1,x2),x3).numpy()

84.0